version: "3.4"
services:
  frpc:
    image: muscipular/frpc
    volumes:
      - /root/etc/frpc/frpc.ini:/app/frpc.ini
    networks: 
      - host
    deploy:
      replicas: 1
      restart_policy:
        # condition: on-failure
        delay: 5s
networks:
  host:
    external: true
    # name: "host"
  # nonet:
    # external: true
    # name: "none"