version: "3.4"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        # condition: on-failure
        delay: 5s
    # volumes: []
    logging:
      driver: json-file
      options:
        max-size: 3m
networks:
  host:
    external: true
    # name: "host"
  # nonet:
    # external: true
    # name: "none"